export const VIEWPORT_WHEEL_SMOOTHING = 15;
export const VIEWPORT_DECELERATION_FRICTION = 0;
export const VIEWPORT_INIT_DELAY_MS = 0;

export const DEFAULT_ZOOM_STEP = 0.2;

export const TILEMAP_MIN_ZOOM_SCALE = 0.05;
export const TILEMAP_MAX_ZOOM_SCALE = 50;

export const TILESET_MIN_ZOOM_SCALE = 0.5;
export const TILESET_MAX_ZOOM_SCALE = 50;

export const SELECTED_TILE_MIN_ZOOM_SCALE = 0.25;
export const SELECTED_TILE_MAX_ZOOM_SCALE = 64;
export const SELECTED_TILE_FIT_MIN_ZOOM_SCALE = 0.25;
export const SELECTED_TILE_FIT_MAX_ZOOM_SCALE = 32;
export const SELECTED_TILE_FIT_PADDING = 64;
